import { readFile, writeFile } from 'node:fs/promises';

/*
The catalogue belongs to mcp-server: it owns the argument schemas, so it owns their hashes. The
bot only has to agree, and a hash it derived itself would agree with nothing but itself. This
copies the values out of catalog.json into a file that is committed and reviewed, so a catalogue
change shows up as a diff here rather than as one tool quietly going dark at runtime.
*/

const DEFAULT_CATALOG = '../mcp-server/catalog/catalog.json';
const TARGET = 'src/rpc/catalog-hashes.ts';
const KIND = 'mineflayer';

interface CatalogTool {
  name: string;
  route: string;
  kinds: string[];
  exclusive: boolean;
  wireSchemaHash: string;
}

interface Catalog {
  catalogVersion: string;
  protocol: number;
  tools: CatalogTool[];
}

const source = process.argv[2] ?? process.env.CATALOG ?? DEFAULT_CATALOG;
const catalog = JSON.parse(await readFile(source, 'utf8')) as Catalog;

const mine = catalog.tools
  .filter((tool) => tool.route === 'rpc' && tool.kinds.includes(KIND))
  .sort((a, b) => a.name.localeCompare(b.name));

const entries = mine
  .map((tool) => `  '${tool.name}': '${tool.wireSchemaHash}',`)
  .join('\n');

const exclusive = mine
  .filter((tool) => tool.exclusive)
  .map((tool) => `  '${tool.name}',`)
  .join('\n');

const file = `/* Generated by scripts/sync-catalog.ts from ${source}. Do not edit by hand. */

export const CATALOG_VERSION = '${catalog.catalogVersion}';

export const WIRE_SCHEMA_HASHES: Readonly<Record<string, string>> = {
${entries}
};

/* Tools that move the bot or the world. Two of these at once would fight each other. */
export const EXCLUSIVE_TOOLS: ReadonlySet<string> = new Set([
${exclusive}
]);
`;

await writeFile(TARGET, file);
process.stdout.write(`${TARGET}: ${mine.length} ${KIND} tools from catalogue ${catalog.catalogVersion}\n`);
